---
# handlers file for otrs

- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
  become: true

- name: Restart Apache
  service: 
    name: httpd
    state: restarted
  become: true