---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: vagrant-centos7
    box: generic/centos7
    memory: 1024
    cpus: 1
provisioner:
  name: ansible
  lint: |
    ansible-lint
  inventory:
    links:
      #hosts:
      group_vars: ../../../../group_vars/
      #host_vars:
scenario:
  name: default
  test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - prepare
  - converge
  - verify
verifier:
  name: goss