---
# tasks file for common
- name: Install Epel repository and needed packages
  yum: 
    name: [ "epel-release", "chrony", "bash-completion", "vim", "perl" ]
    state: present

- name: start ntp service
  service: 
     name: chronyd 
     state: started 
     enabled: yes
  
- name: disable Selinux
  selinux: 
    state: disabled
  
- name: Copy NTP config file
  template: 
    src: chrony.conf.j2 
    dest: "{{ ntp_dir }}/chrony.conf"
  notify: restart chronyd

- name: Open port 443
  firewalld:
    service: https
    permanent: true
    state: enabled

- name: Open Port 80
  firewalld:
    service: http
    permanent: true
    state: enabled

- name: Restart Firewalld
  service: 
    name: firewalld
    state: restarted
