---
# tasks file for otrs

- name: Get privileges
  block:

    - name: Ensure curl is installed
      yum: 
        name: curl
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Download MariaDB Repo Script
      get_url:
        url: https://downloads.mariadb.com/MariaDB/mariadb_repo_setup
        dest: ~/
        mode: '755'

    - name: Enable official MariaDB Repo 
      command: /bin/bash ~/mariadb_repo_setup

    - name: Install MariaDB 10.4 packages
      yum:
        name: ["MariaDB-server", "MariaDB-client"]
        state: present

    - name: Start and enable MariaDB
      service: 
        name: mariadb
        state: started
        enabled: yes

    - name: Configure mariadb with zotrs.cnf
      template:
        src: zotrs.cnf.j2
        dest: /etc/my.cnf.d/zotrs.cnf
      notify: Restart MariaDB

#- name: Set MariaDB Character to UTF8
#  template: 
#    src: server.cnf.j2
#    dest: /etc/my.cnf.d/server.cnf
#  notify: Restart MariaDB

    - name: Install PyMySQL packages
      yum:
        name: ["python2-PyMySQL.noarch", "python36-PyMySQL.noarch"]

    - name: configure MySQL root password
      community.mysql.mysql_user:
        #login_host: "localhost"
        login_unix_socket: /var/lib/mysql/mysql.sock
        #login_user: "root"
        login_password: "{{ mysql_password }}"
        name: root
        password: "{{ mysql_password }}"
        state: present

    - name: install otrs package
      yum:
        name:  https://ftp.otrs.org/pub/otrs/RPMS/rhel/7/otrs-6.0.30-02.noarch.rpm
        state: present

    - name: Start and enable Apache
      service: 
        name: httpd
        state: started
        enabled: yes
      

    - name: install additional packages
      yum:
        name: [ "mod_ssl", "perl-DBD-mysql", "perl-App-cpanminus.noarch", "perl(Text::CSV_XS)", "perl(ModPerl::Util)", "perl(YAML::XS)", "perl(JSON::XS)", "perl(Authen::NTLM)", "perl(Mail::IMAPClient)", "perl(Crypt::Eksblowfish::Bcrypt)", "perl(Encode::HanExtra)" ] 
        state: present


    - name: Copy Private key
      template: 
        src: eodatacenter.com.key
        dest: "{{ private_key_path }}"
      become: true
    
    - name: Copy SSL Certificate
      template:
        src: eodatacenter.com.pem
        dest: "{{ certificate_path }}"
      become: true

    - name: Copy otrs config file
      template:
        src: zzz_otrs.conf.j2
        dest: /etc/httpd/conf.d/zzz_otrs.conf
      become: true

    - name: Copy ssl config file
      template:
        src: ssl.conf.j2
        dest: /etc/httpd/conf.d/ssl.conf
      become: true
      notify: Restart Apache

    - name: Install getpagespeed package
      yum: 
        name: "https://extras.getpagespeed.com/release-el7-latest.rpm"
        state: present

    - name : Install Perl-Moo
      yum: 
        name: [ "perl-Moo" ]
        state: present

    - name: Install required version of IO::Socket::SSL
      community.general.cpanm:
        name: "IO::Socket::SSL"
        version: "2.068"

    - name: Copy Perl Module installer
      template:
        src: installPerlModules.sh
        dest: ~/installPerlModules.sh

    - name: Install other packages with cpan command
      command: /bin/bash ~/installPerlModules.sh
  
  become: true